/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Scene2RouteImport } from './routes/scene-2'
import { Route as Scene3RouteImport } from './routes/scene-3'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Scene2Route = Scene2RouteImport.update({
  id: '/scene-2',
  path: '/scene-2',
  getParentRoute: () => rootRouteImport,
} as any)
const Scene3Route = Scene3RouteImport.update({
  id: '/scene-3',
  path: '/scene-3',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/scene-2': typeof Scene2Route
  '/scene-3': typeof Scene3Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/scene-2': typeof Scene2Route
  '/scene-3': typeof Scene3Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/scene-2': typeof Scene2Route
  '/scene-3': typeof Scene3Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/scene-2' | '/scene-3'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/scene-2' | '/scene-3'
  id: '__root__' | '/' | '/scene-2' | '/scene-3'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Scene2Route: typeof Scene2Route
  Scene3Route: typeof Scene3Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scene-2': {
      id: '/scene-2'
      path: '/scene-2'
      fullPath: '/scene-2'
      preLoaderRoute: typeof Scene2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scene-3': {
      id: '/scene-3'
      path: '/scene-3'
      fullPath: '/scene-3'
      preLoaderRoute: typeof Scene3RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Scene2Route: Scene2Route,
  Scene3Route: Scene3Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
